version: "3.9"

networks:
  internal:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: "${APP_NAME}-server"
    hostname: "${APP_NAME}"
    ports:
      - "${APP_PORT}:80"
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    networks:
      - internal

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: "${APP_NAME}-mssql"
    hostname: "${APP_NAME}-mssql"

    ports:
      - ${DB_PORT}:1433
    volumes:
      - ./docker/db/data:/var/opt/mssql/data
      - ./docker/db/log:/var/opt/mssql/log
      - ./docker/db/backup:/var/opt/mssql/backup
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASS}
    networks:
      - internal

volumes:
  db_data:
  db_admin_data:
